### ISSUE TITLE
Problem of CalendarDidLoadNextPage

### ISSUE THREAD

**Issue by mingxuler** [jonathantribouharet/JTCalendar#343]
Hello Jonathan;
When I send the network request as below,the next mouth show not in the right.If did not set the the request,slipe to the next mouth is okay.

- (void)calendarDidLoadNextPage:(JTCalendarManager *)calendar
{

    NSDate * date =  [calendar date];
    // send a network request for next mouth events
    [self findAttendanceRequest:date];
}

![didload](https://user-images.githubusercontent.com/19489591/27329664-0ba8737e-55e9-11e7-8ccd-ccc526f38e03.jpeg)

**Comment by arvincong** [comment]
you can   DispatchQueue.global().async{
             sleep(1);
            DispatchQueue.main.async{
                   //do net work request  
             }
}

**Comment by vikrant-Ios** [comment]
@mingxuler your issue has been resolved ?
please tell how to resolve this type issue .

**Comment by ZhouguanyuIOS** [comment]
@vikrant-Ios your issue has been resolved ?
please tell how to resolve this type issue .

**Comment by vikrant-Ios** [comment]
Hi,

No, it wasn't resolved yet so, i changed the flow to save time.

Thanks & Regards

Vikrant Rohilla
+91 9254575005
vikrant.rohilla.30@gmail.com
